name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image and push to registry
      uses: cloudposse/github-action-docker-build-push@1.11.0
      with:
        registry: docker.io
        image_name: chip8-rust
        login: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
